name: pass unit tests

on:
  push:
  pull_request:
    branches: [main, develop]
    paths:
    - '**.cs'
    - '**.csproj'

env:
  DOTNET_VERSION: '9.0.300' # The .NET SDK version to use

jobs:
  pass-backend-unit-tests:

    name: Pass backend unit tests on ${{matrix.os}}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Test backend
      run: dotnet test --no-restore --verbosity normal